# Generated by Django 4.2.1 on 2023-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_regmodel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel1',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
