# Generated by Django 4.2.1 on 2023-07-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_withmoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='ministatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.IntegerField(choices=[('withdraw', 'withdraw'), ('deposite', 'deposite'), ('all', 'all')])),
            ],
        ),
    ]
